app = "cargowetao"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = 9761
APP_PSQ_DSN="postgres://cargo:QmIiLlyBkO70@ep-summer-king-59958647.eu-central-1.aws.neon.tech/koyebdb"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 9761
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[build]
dockerfile = "Dockerfile"